name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Stap 1: Checkout de code uit de repository
    - uses: actions/checkout@v4

    # Stap 2: Build de Docker image
    - name: Build the Docker image
      run: docker build -t bpimg -f docker/Dockerfile .

    # Stap 3: Build de thesis bestanden
    - name: Build the proposal
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh voorstel

    - name: Build the thesis
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh bachproef

    - name: Build the poster
      run: docker run --rm -v "$PWD":/bp bpimg sh /bp/docker/render_thesis.sh poster

    # Stap 4: Maak de GitHub release aan
    - name: Create GitHub Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        RELEASE_TAG="v$(date +'%Y%m%d%H%M%S')"  # Maak een unieke release tag gebaseerd op de timestamp
        gh release create $RELEASE_TAG output/*.pdf output/*.log --title "Thesis Output" --notes "Deze release bevat de thesis outputbestanden."

    - uses: actions/upload-artifact@v4
      name: Upload artifacts
      with:
        name: output
        path: |
          output/*.pdf
          output/*.log
        if-no-files-found: error        
